version: '3'
services:
  web_core:
    image: nakahararuu/zion_resource
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./test_data/movie:/srv
      - ./test_data/Caddyfile_core:/etc/Caddyfile
    expose:
      - '2015'
    restart: always
  backend:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/backend_api:/home/node/app
    expose:
      - '8000'
    command: 'npx json-server --watch --host 0.0.0.0 --port 8000 ./db.json'
    restart: always
  auth:
    image: tarent/loginsrv
    expose:
      - '8080'
    environment:
      - LOGINSRV_BACKEND=provider=simple,${USER_NAME}=${PASSWORD}
      - LOGINSRV_JWT_EXPIRY=${JWT_EXPIRY}
      - LOGINSRV_JWT_SECRET=${JWT_SECRET}
    restart: always
  auth_dummy:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/auth_api:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && npm start"
    restart: always
