version: '3'
services:
  web:
    environment:
      - CADDYPATH=/etc/caddycerts
      - HOST_NAME=${HOST_NAME}
    volumes:
      - '$HOME/.caddy:/etc/caddycerts'
      - '$PWD/Caddyfile_front:/etc/Caddyfile'
    ports:
      - '2015:2015'
    image: abiosoft/caddy
  node:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && npm run build && npm run start"
  backend:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/:/home/node/app
    expose:
      - '8000'
    command: 'npx json-server --watch --static ./ --host 0.0.0.0 --port 8000 ./db.json'
  auth:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./test_data/auth_api:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && npm start"
  resource:
    image: nakahararuu/zion_resource
    environment:
      - JWT_SECRET=my_secret
    volumes:
      - '$HOME/.caddy:/etc/caddycerts'
      - ./test_data:/srv
      - ./Caddyfile_resource:/etc/Caddyfile
    expose:
      - '2015'

