version: '3'
services:
  web:
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - '$HOME/.caddy:/etc/caddycerts'
      - '$PWD/Caddyfile:/etc/Caddyfile'
    ports:
      - '80:80'
      - '443:443'
      - '2015:2015'
    image: abiosoft/caddy
  node:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && npm run build && npm run start"
  backend:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/:/home/node/app
    expose:
      - '8000'
    command: 'npx json-server --watch --static ./ --host 0.0.0.0 --port 8000 ./db.json'
