version: '3'
services:
  web_surface:
    environment:
      - CADDYPATH=/etc/caddycerts
      - HOST_NAME=${HOST_NAME}
    volumes:
      - '$HOME/.caddy:/etc/caddycerts'
      - '$PWD/Caddyfile_surface:/etc/Caddyfile'
    ports:
      - '2015:2015'
    image: abiosoft/caddy
  node:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && ${NUXT_CMD}"
  web_core:
    image: nakahararuu/zion_resource
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./test_data:/srv
      - ./Caddyfile_core:/etc/Caddyfile
    expose:
      - '2015'
  backend:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/:/home/node/app
    expose:
      - '8000'
    command: 'npx json-server --watch --static ./ --host 0.0.0.0 --port 8000 ./db.json'
  auth:
    image: tarent/loginsrv
    expose:
      - '8080'
    command: "-jwt-secret ${JWT_SECRET} -simple ${USER_NAME}=${PASSWORD}"
