version: '3'
services:
  web_surface:
    environment:
      - CADDYPATH=/etc/caddycerts
      - HOST_NAME=${HOST_NAME}
    volumes:
      - '$HOME/.caddy:/etc/caddycerts'
      - '$PWD/Caddyfile:/etc/Caddyfile'
    ports:
      - '80:80'
      - '443:443'
      - '2015:2015'
    image: abiosoft/caddy
    restart: 'no'
  node:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - CORE_URL=${CORE_URL}
    volumes:
      - ./:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && ${NUXT_CMD}"
    restart: 'no'
